<?php

$labels = [];
$labels['rule_min_length'] = 'Minimum $count characters';
$labels['rule_uppercase']  = 'Minimum $count uppercase letter';
$labels['rule_lowercase']  = 'Minimum $count lowercase letter';
$labels['rule_digit']      = 'Minimum $count digit';
$labels['rule_special']    = 'Minimum $count special character';
$labels['complexity_not_met'] = 'Password does not meet complexity requirements';
